# Generated by Django 3.1.7 on 2021-03-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's provided name", max_length=255, unique=True)),
                ('public_key', models.TextField(help_text="Client's provided public-key used in message sending", max_length=271)),
                ('last_seen', models.DateTimeField(auto_now_add=True, help_text='The last date and time the server received a request from the client')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('content', models.BinaryField(help_text='The message content')),
                ('from_client', models.ForeignKey(help_text='The message sender', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='serverapp.client')),
                ('to_client', models.ForeignKey(help_text='The message recipient', on_delete=django.db.models.deletion.CASCADE, related_name='waiting_messages', to='serverapp.client')),
            ],
        ),
    ]
