# Generated by Django 3.1.7 on 2021-03-02 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import serverapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's provided name", max_length=255, unique=True)),
                ('public_key', models.BinaryField(help_text="Client's provided public-key used in message sending", max_length=160)),
                ('last_seen', models.DateTimeField(blank=True, help_text='The last date and time the server received a request from the client', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Unique identifier', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967295)])),
                ('message_type', enumchoicefield.fields.EnumChoiceField(enum_class=serverapp.models.Message.MessageType, max_length=3)),
                ('content', models.TextField(help_text='The message content')),
                ('from_client', models.ForeignKey(help_text='The message sender', on_delete=django.db.models.deletion.CASCADE, to='serverapp.client')),
                ('to_client', models.ForeignKey(help_text='The message recipient', on_delete=django.db.models.deletion.CASCADE, to='serverapp.client')),
            ],
        ),
    ]
