# Generated by Django 3.1.7 on 2021-03-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_client',
            field=models.ForeignKey(help_text='The message sender', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='serverapp.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_client',
            field=models.ForeignKey(help_text='The message recipient', on_delete=django.db.models.deletion.CASCADE, related_name='waiting_messages', to='serverapp.client'),
        ),
    ]
